####################################################
##                                                ##
##                  qEssentials                   ##
##                 Configuration                  ##
##                                                ##
####################################################
# Messages language. More languages you can find on github
# http://github.com/xVacuum/qEssentialsReloaded
# Available to download (on github): pl
# Available as default: en
language: en
# Help page length (commands per page)
help-page-length: 10
# Quit/Join formats
quit-format: '&c{PLAYER} left the game.'
join-format: '&a{PLAYER} joined the game.'
# Kick temporary ban in seconds
kick-temporary-ban: 20
# Disabled worlds
disabled-worlds:
  - 'blockedworld'
  - 'blockedworld2'
# Kill messages
kill-messages-disabled: false
# Database
database:
  mysql: false
  host: localhost
  port: 3306
  user: root
  pass: password
  name: database
####################################################
##                   Database                     ##
####################################################
# MySQL configuration. 
database:
    # Type `true` in `mysql` to enable.
    # `false` means the mysql function is disabled, and plugin uses SQLite (file *.db)
    mysql: false
    # MySQL port
    port: 3306
    # MySQL host (ip address or localhost if server is local)
    host: localhost
    # MySQL username
    user: root
    # Database name
    name: database_name
####################################################
##                    Helpop                      ##
####################################################
helpop-delay: 10

####################################################
##                  Teleporting                   ##
####################################################
# Delay after command execute. In seconds.
delay: 10
# Spawn teleport effects
teleport-spawn-effects: true

####################################################
##                     Homes                      ##
####################################################
# Default maximum amount of homes
max-homes: 3

####################################################
##                     Chat                       ##
####################################################
# Default chat state
chat-default-enabled: true
# Default chat format
chat-format: "&8[&c{HEALTH}/10.0&8] &8[&e{FOOD}/10&8] &7{PLAYER}&8: &f{MESSAGE}"
# Chat slowdown (in seconds)
chat-slowdown: 3
# Group chat
groups:
  default: '&7{PLAYER}&8: &f{MESSAGE}'
  admin: '&8[&4Admin&8] &7{PLAYER}&8: &f{MESSAGE}'

####################################################
##                  First join                    ##
####################################################
# First join message
first-join-message: '&ePlayer {PLAYER} is for first time on our server!'
# First-join kit
first-join-kit: custom
####################################################
##                     Kits                       ##
####################################################
kits:
  custom:
    cooldown: 20
    items:
      - 'apple 5 Custom_Apple This_is;&dcolored_lore fireaspect:1;sharpness:3'
      - 'diamond_sword 1 &6&lExcalibur &eMagic_sword_from;&eThe_dark_sides_of;&ethe_world fireaspect:10;sharpness:10;unbreaking:10'

####################################################
##                  AutoMessage                   ##
####################################################
# delay between messages in seconds
automessage-delay: 35
# messages
automessages:
  - '&aDefault message #1'
  - '&bDefault message #2'
  - '&cDefault message #3'
  
# End of file -> Seriously... stop, this is stupid.
